### ISSUE TITLE
字体文件好像加载不了!

### ISSUE THREAD

**Issue by NewbieGood** [waite0603/Resume-vCard-Collection#2]
从B站过来的, Up有部分的模板字体加载不出来而且控制台有报错!

![image](https://github.com/waite0603/Resume-vCard-Collection/assets/146636889/c7b79975-c01b-4be5-8b9d-4e3c4d2248df)

**Comment by Waite0603** [comment]
这是因为使用了 `fonts.googleapis.com` 的 `CSS` 资源, 有可能国内网络原因或者你的代理规则屏蔽了!
以下有两种解决方式哈:
1. 检查代理/ 更换 Vpn 的节点,
2. (推荐) 你也可以更改模板中的字体 Css 引用, 改成国内方便访问的资源路径/ 本地!
